### ISSUE TITLE
Error with Houdini 20.0.547

### ISSUE THREAD

**Issue by jomaro110** [grabanton/lighter#1]
I am having error when calling the node:

There is an error in the Lighter script.

```
Traceback (most recent call last):
     File "C:/Users/Admin/Documents/houdini20.0/My_H_plugins/lighter-main/python_panels/lighter.pypanel", line 1, in <module>
     <?xml version="1.0" encoding="UTF-8"?>
     File "C:\Program Files\Side Effects Software\Houdini 20.0.547\python310\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
     return original_import(name, *args, **kwargs)
    ModuleNotFoundError: No module named 'lighter'
    
```

**Comment by grabanton** [comment]
I'll check. I think problem with python version. Try to duplicate python3.9libs folder and rename it to python3.10libs. I'll fix it little bit later.

**Comment by oliverban** [comment]
> I'll check. I think problem with python version. Try to duplicate python3.9libs folder and rename it to python3.10libs. I'll fix it little bit later.

Did you end up fixing this or is it still the case we need to do this? :) And when you say duplicate, you mean from where? :D <3
